### ISSUE TITLE
Нерабочая ссылка на спецификацию в Readme

### ISSUE THREAD

**Issue by TeroBlaZe** [Ensemplix/ENBT#1]
Годная либа, благодарствую 👍

**Comment by ensirius** [comment]
Исправлено. Спасибо. К сожалению, есть случаи когда библиотека не может правильно сработать. В частности, иногда ENUM присылаются как часть их названия, а не как порядок в массиве. Думаю, мне стоит еще раз взглянуть на эти проблемы и возможно их получиться исправить

**Comment by TeroBlaZe** [comment]
@ensirius да я заметил, я тут еще косяк обнаружил.
