### ISSUE TITLE
Тип Boolean не поддерживается, ошибка сохранения

### ISSUE THREAD

**Issue by TeroBlaZe** [Ensemplix/ENBT#4]
У библиотеки проблема с сохранением булеанов, она их вообще не поддерживает, судя из спецификации. Отсюда если сохранить булеан с помощью библиотеки, то преобразуется он уже в nbt сompound tag без значения, а при последующем чтении такого файла вылезет ошибка.
Забавно, что эта багулина увельнула от тестов))) А всё потому, что в тестах не происходит записи ServerList, а только чтение из файла)

**Comment by ensirius** [comment]
Проблема исправлено. Приношу извинения за неудобства.
